// Refreshes the offline fallback: downloads the three phase tabs from the
// Google Sheet into public/data/ and stamps lib/snapshot-date.ts.
// Run before deploying so the fallback never drifts far from the sheet.
import { writeFileSync } from 'node:fs';

const SHEET =
  'https://docs.google.com/spreadsheets/d/1fNmXMehYd2Y6a46WbISAThfOHLIvTKf0ytYv9r9UFfM';
const GIDS = [0, 897242695, 804851942];

for (const [i, gid] of GIDS.entries()) {
  const res = await fetch(`${SHEET}/export?format=csv&gid=${gid}`);
  if (!res.ok) throw new Error(`Tab ${i + 1} failed: HTTP ${res.status}`);
  const text = await res.text();
  const rows = text.split(/\r?\n/).filter(Boolean).length - 1;
  if (!text.startsWith('Name,') || rows < 1)
    throw new Error(`Tab ${i + 1} does not look like the router sheet`);
  writeFileSync(`public/data/phase${i + 1}.csv`, text);
  console.log(`phase${i + 1}.csv: ${rows} rows`);
}
const date = new Date().toLocaleDateString('en-MY', {
  timeZone: 'Asia/Kuala_Lumpur',
  day: 'numeric',
  month: 'short',
  year: 'numeric',
});
writeFileSync(
  'lib/snapshot-date.ts',
  `// Generated by \`pnpm snapshot\`. Do not edit by hand.\nexport const SNAPSHOT_DATE = '${date}';\n`,
);
console.log(`Snapshot date: ${date}`);
